version: '3.7'

services:
  echo-notes-service:
    build: .
    ports:
      - 1323:1323
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mariadb-service
  
  mariadb-service:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306
    volumes:
      - /home/nadir/echovolume:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge